### ISSUE TITLE
WSAFacebookAPI causes build fail when -warnaserror+ is used

### ISSUE THREAD

**Issue by Alexees** [ClaytonIndustries/WSANative#1]
Building for UWP, there is one line of code that causes a warning, in the mentioned case an error even:

.cs: Line 38: In case of the absent of NETFX_CORE, _dxSwapChainPanel is never assigned to and throws that warning.
If fixed that along with missing NETFX_CORE directives

[WSAFacebookApi.zip](https://github.com/ClaytonIndustries/WSANative/files/3406146/WSAFacebookApi.zip)

I'm using the package in combination with the Microsoft MixedRealityToolkit and they recently changed to using -warnaserror+

**Comment by ClaytonIndustries** [comment]
Thanks for reporting.

You can disable the warning as error in your visual studio settings.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Alexees** [comment]
Hi there,

I know I can do that, but it would be nicer if the asset did not generate anything at all.
I’d like to concentrate on my own warnings.

Best regards,

Alexander Seeck
Agile Octopus
email. as@holospaces.com<mailto:as@holospaces.com>
web. www.holospaces.com<http://www.holospaces.com>
phone. +49 3012085156
------------------------------------------------------------------
HoloSpaces GmbH
Europaallee 27d
66113 Saarbrücken
email. hello@holospaces.com<mailto:hello@holospaces.com>
Geschäftsführer: Christian Glessner
Amtsgericht Saarbrücken HRB 101021
