### ISSUE TITLE
.NET backend on track of deprecation, porting all API to support IL2CPP?

### ISSUE THREAD

**Issue by heshuimu** [ClaytonIndustries/WSANative#2]
I'm especially interested in the WebView because I am implementing third party OAuth sign-in in my project, but I already moved on to 2019.1 and using .NET is not an option due to engineering decisions and deprecation. In the doc the WebView API is marked as .NET only.

**Comment by ClaytonIndustries** [comment]
Hi Tommy. Unfortunately due to the way IL2CPP works its a lot more
difficult to support native windows controls, which is why we don't support
WebView at this time.

**Comment by ClaytonIndustries** [comment]
Support has been added in version 2.0 of the plugin
