### ISSUE TITLE
In my visual studio solution I can't find MainPage.xaml.cs only MainPage.xaml file

### ISSUE THREAD

**Issue by PabloBuitrago** [ClaytonIndustries/WSANative#3]
Hi ClaytonIndustries,

I currently have a Unity project and need a native web browser.

I am using the WSANativeWebView class with the function Create (int x, int y, int width, int height, Uri uri).

I work with Unity 2019.4.8 and I can't find the MainPage.xaml.cs file, I can only see the MainPage.xaml file in my Visual Studio solution. (How to explain the documentation in WebView the Setup section)

![image](https://user-images.githubusercontent.com/31513526/105371906-5ffdea00-5c05-11eb-9aa6-76c99fc10006.png)

**Comment by ClaytonIndustries** [comment]
Looks like a IL2CPP project, which we don't support the webview in

**Comment by PabloBuitrago** [comment]
I have been doing a lot of research on the subject, apparently in new versions of Unity the option to compile as project in C# no longer appears in Windows Platform as there were performance problems. (I think is deprecated)

Old
![image](https://user-images.githubusercontent.com/31513526/105574704-943cec00-5d66-11eb-8b66-ac245708713a.png)

New
![image](https://user-images.githubusercontent.com/31513526/105574735-d82ff100-5d66-11eb-9baa-3613c01a0ef8.png)

and the IL2CPP is required in Windows Platform in Unity new versions

Right now I am investigating how to insert this line of code in a project compiled in C++.

`CI.WSANative.Web.WSANativeWebView.Configure(GetSwapChainPanel())`

**Comment by ClaytonIndustries** [comment]
I'm not entirely sure you can, that's why we didn't add support for everything in IL2CPP

**Comment by ClaytonIndustries** [comment]
Support has been added in version 2.0 of the plugin
