### ISSUE TITLE
How to load html content in webview directly ,not url link？

### ISSUE THREAD

**Issue by jiangjkd** [ClaytonIndustries/WSANative#6]
How to load html content in webview directly ,not url link？

**Comment by ClaytonIndustries** [comment]
Hi, if the webpage is included in your uwp solution then you can use `webView.Navigate(new Uri("ms-appx-web:///SomeFile.html"));`
If it's in your apps local or temp folders then `webView.Navigate(new Uri("ms-appdata:///local/SomeFile.html"));`
