### ISSUE TITLE
WSANativeFilePicker.PickSingleFile - how to get file path?

### ISSUE THREAD

**Issue by CDAfonso** [ClaytonIndustries/WSANative#7]
Hi! 
Is there a way to get the file path of the file chosen from PickSingleFile?

Thanks.

**Comment by ClaytonIndustries** [comment]
Hey, yes there is. The result object with gets returned by that function has a "Path" property on it

**Comment by CDAfonso** [comment]
> Hey, yes there is. The result object with gets returned by that function has a "Path" property on it

My god! Didn't figured that out... Thank you so much for all your awesome help.
