### ISSUE TITLE
Error with facebook module integration in latest 2.4 plugin version

### ISSUE THREAD

**Issue by devauk** [ClaytonIndustries/WSANative#8]
Hi,

I have updated WSANative package to the latest version 2.4 in my project. After integration I have followed the below steps in visual studio project as mentioned in the integration document

1. Open the solution and add the Nuget package Microsoft.UI.Xaml
2. Download [this file](https://raw.githubusercontent.com/ClaytonIndustries/WSANative/master/Documents/FacebookManager.h) and add it to the project which has the same name as your game. Make sure it is in the same folder as MainPage.xaml
3. Open MainPage.xaml.cpp and add the following includes near the top
```
#define GENERATED_PROJECT 1
#include "WSAFacebookBridge.h"
#include "FacebookManager.h"
```
4. At the bottom of the MainPage.xaml.cpp constructor add the following line
`FacebookManager::Initialise(m_DXSwapChainPanel);`
5. Open the apps manifest file and add the internet client capability

I am getting following error, 

MainPage.xaml.cpp(74,9): error C2653: 'FacebookManager': is not a class or namespace name
MainPage.xaml.cpp(74,26): error C3861: 'Initialise': identifier not found

How can I resolve thi issue? Do I need to set any properties for FacebookManager.h while adding?

Unity version : 2020.3.46f1
Visual studio : Visual Studio professional 2019

Attached MainPage.xaml.cpp

![fberror](https://github.com/ClaytonIndustries/WSANative/assets/8436644/c817fe08-5d67-40fc-8bf3-b88fe30f428e)
[MainPage.xaml.cpp.zip](https://github.com/ClaytonIndustries/WSANative/files/12039994/MainPage.xaml.cpp.zip)

**Comment by ClaytonIndustries** [comment]
How did you add the FacebookManager.h file to the project? By dragging or by right click add. Dragging sometimes doesn't work so do the right click add method

**Comment by ClaytonIndustries** [comment]
Also note that you need to be using Unity 2021 or above for Facebook login to function properly.

**Comment by devauk** [comment]
> How did you add the FacebookManager.h file to the project? By dragging or by right click add. Dragging sometimes doesn't work so do the right click add method

I tried with right click and add method

**Comment by devauk** [comment]
> Also note that you need to be using Unity 2021 or above for Facebook login to function properly.

ok, noted

**Comment by devauk** [comment]
Issue is resolved after updating the unity version
