### ISSUE TITLE
input problem

### ISSUE THREAD

**Issue by mhshimP1S** [ClaytonIndustries/WSANative#9]
Hi,

Thank you for your project. It works well with my game.
However, I couldn't type alphanumeric characters in the text input(ID/Password).
I was able to type in Korean, but not in English.
So, I had to copy and paste my email address and password from another text.😂

Can you help me figure out what the problem is?

I used below version
unity : 2020.3.47f1
Visual studio Pro 2019 : 16.11.27
Microsoft.UI.Xaml NuGet pacackge : 2.8.4, 2.8.5

**Comment by ClaytonIndustries** [comment]
Hi, unfortunately there's a bug in Unity 2020 that means it doesn't work well with the webview. You'll need to upgrade to 2021 or later for it to work with English

**Comment by mhshimP1S** [comment]
I solved it by upgrading the project version to 2021.3.X.
It's works well now. Thanks a lot! :)
